apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: dvwa
  region: eu-central-1
  version: "1.28"
nodeGroups:
  - name: worker-group
    instanceType: m7g.medium
    desiredCapacity: 2
    privateNetworking: true
